sudo: false
language: rust
cache: cargo
rust:
 - stable
 - beta
 - nightly
os:
 - linux
# - osx # Disabled because of long wait times and spurious travis errors
matrix:
    allow_failures:
        - rust: nightly
env:
    - RUST_BACKTRACE=1
